### ISSUE TITLE
Should the package work?

### ISSUE THREAD

**Issue by PallHaraldsson** [citkane/SimpleWebsockets.jl#3]
Hi,

I was googling and found your package by accident. I realize it's not registered, so feel free to ignore me.

I tried sever combinations of versions of your package, and Julia versions, and all failed like:
```
import Pkg; Pkg.add(url="https://github.com/citkane/SimpleWebsockets.jl", rev="v0.2,2")

julia> using SimpleWebSockets
ERROR: ArgumentError: Package SimpleWebSockets not found in current path:
- Run `import Pkg; Pkg.add("SimpleWebSockets")` to install the SimpleWebSockets package.

Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:871
```

I tried 1.7.0-rc3 and a recent master, then thinking those might be the problem then 1.6, what the output above is (strictly for 1.6.0-rc2 that I had handy).

I was thinking could your package be a (drop-in) replacement for WebSockets.jl? That would be one workaround to (if faster):

https://discourse.julialang.org/t/using-web-packages-together-is-much-slower-e-g-0-2-sec-0-7-sec-7-8-sec/72075

Note also, you have a typo, you likely wanted to tag v0.2.2, not with a comma. I don't know Git[hub] well enough, if you can undo that. Might be enough to tag v0.2.3 for other users not to get confused (in case of bad eyesight...). I'm not sure what you could have done if you actually had registered such a version. You probably couldn't have since:

```
julia> v"0.2,2"
ERROR: LoadError: ArgumentError: invalid version string: 0.2,2
```

If/ehn you register you may want to rename SimpleWebsockets.jl to SimpleWebSockets.jl for same spelling as the capital S in WebSockets for the other package and its page at Wikipedia (seems official that way).

**Comment by citkane** [comment]
Hi @PallHaraldsson ,

Apologies for the slow response, I have been AFK while working in another profession.

"SimpleWebsockets" **should**, and indeed **does work** .

**Yes**, it can be a drop-in replacement for "WebSockets.jl", and it offers a comprehensive high level interface which is easy to use as described in the [documentation](https://citkane.github.io/SimpleWebsockets.jl/stable/).

You are getting an error because of a typo that you have made: `julia> using SimpleWebSockets` should be `julia> using SimpleWebsockets`

This comes to your suggestion to spell `SimpleWebsockets` as `SimpleWebSockets` to match the preferred nomenclature for generic "WebSockets" on Wikipedia, etc.

I agree with you, but  SimpleWebsockets has already been registered on JuliaHub [here](https://juliahub.com/ui/Packages/SimpleWebsockets/6fptm) for some years. A name change is non-trivial.

In my absence, my co-maintainer @zahachtah did some work on v0.2.2 (which updated dependencies for later Julia versions).
I did not see the `v0.2,2` typo, so he must have fixed that.

v0.2.2 was on Github only, and did not go to JuliaHub because of breaking dependency issues which affected the testing code. I fixed this yesterday, so v0.2.2 is now on JuliaHub.

**Installation should be**: `Pkg.add("SimpleWebsockets")` to get the latest v0.2.2

**Comment by PallHaraldsson** [comment]
@citkane thanks for answering. @zahachtah

>your suggestion to spell SimpleWebsockets as SimpleWebSockets to match the preferred nomenclature

On that I know you can register a package as a subpackage of your package. I don't know much about it, I believe e.g. GLMakie.jl is a subpackage of Makie.jl at same github. But with different functionality... I'm not sure if this mechanism could be used to add a synonym package name, or if there are any (pros and) cons to that. On some way to deprecate the older name. Possibly there's nothing bad with having both names if this would work, and maybe renaming the repo and in docs to the new name to show it's the preferred spelling (most search tools, but not all, are case-insensitive, so that would be an argument against, as consistency might give unintended false-negative search results...).

This discussion/question, as it's a general issue, could me moved/continued elsewhere, e.g. in an issue at the General registry and/or Discourse. Mainly for you would you want to to this if possible?

**Comment by citkane** [comment]
Appreciated.

I have been through one re-name in 2020.

I initially named the package `Websockets`, which was a legal thing to do, but too close to the other package `WebSockets` for the registry maintainers liking, so I was asked to change it.

This resulted in an [update](https://github.com/JuliaLang/Pkg.jl/commit/932c11bf5fc8ee496ce664d86a8a656ff6a9b5d1) in the [package naming guidelines](https://pkgdocs.julialang.org/v1/creating-packages/#Package-naming-guidelines).

At that time, there was no other solution than to delete the package and repo, and start again with a new name. This was OK at that time because the package had no downstream users yet.

At this time, if there is a non-destructive and well described process for renaming by the Julia registry maintainers, I would consider it. Other than that, I feel that renaming is non-essential and best left as it is.

M
